name: Build Docker Image and Push to ECR

on: 
  push:
    branches: [ master ]

env:
  ECR_REPO_PREFIX: assign1-dev
  ECR_REPO: cats dogs
  IMAGE_TAG: v0.1

jobs:
  build:    
    name: Build Image
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        AWS_REGION: us-east-1
        
    - name: Build docker image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
        for repo in $ECR_REPO; do
          cd cats-and-dogs/${repo}/
          ls -ltra
          docker build -t $ECR_REGISTRY/$ECR_REPO_PREFIX-${repo}:$IMAGE_TAG .
          #changing code directory back to original for next iteration
          cd - > /dev/null
        done
